import { Tienda } from "@/types";

export const COMUNAS_SANTIAGO = [
  "Alhué", "Buin", "Calera de Tango", "Cerrillos", "Cerro Navia", "Colina",
  "Conchalí", "Curacaví", "El Bosque", "El Monte", "Estación Central",
  "Huechuraba", "Independencia", "Isla de Maipo", "La Cisterna", "La Florida",
  "La Granja", "La Pintana", "La Reina", "Lampa", "Las Condes", "Lo Barnechea",
  "Lo Espejo", "Lo Prado", "Macul", "Maipú", "María Pinto", "Melipilla",
  "Padre Hurtado", "Paine", "Peñaflor", "Peñalolén", "Pirque", "Providencia",
  "Pudahuel", "Puente Alto", "Quilicura", "Quinta Normal", "Recoleta", "Renca",
  "San Bernardo", "San Joaquín", "San José de Maipo", "San Miguel", "San Pedro",
  "San Ramón", "Santiago", "Talagante", "Til Til", "Vitacura", "Ñuñoa",
];

export const CATEGORIAS: Record<string, { label: string; emoji: string }> = {
  floristeria: { label: "Floristerías", emoji: "🌹" },
  chocolateria: { label: "Chocolaterías", emoji: "🍫" },
  peluches: { label: "Peluches", emoji: "🧸" },
  regalos: { label: "Regalos", emoji: "🎁" },
  joyeria: { label: "Joyería", emoji: "💍" },
  desayunos: { label: "Desayunos", emoji: "🥐" },
  otros: { label: "Otros detalles", emoji: "🎀" },
};

// Datos de ejemplo hasta conectar Supabase
export const TIENDAS_EJEMPLO: Tienda[] = [
  {
    id: "1",
    nombre: "Flores del Alma",
    descripcion: "Arreglos florales únicos para momentos que importan. Diseños personalizados y entrega el mismo día.",
    categoria: "floristeria",
    comuna: "Providencia",
    whatsapp: "+56912345678",
    instagram: "@floresdelalma",
    lat: -33.4311,
    lng: -70.6100,
    activa: true,
  },
  {
    id: "2",
    nombre: "Bloom Santiago",
    descripcion: "Ramos premium con flores importadas. Especialistas en rosas, peonías y orquídeas.",
    categoria: "floristeria",
    comuna: "Las Condes",
    whatsapp: "+56987654321",
    instagram: "@bloomsantiago",
    lat: -33.4073,
    lng: -70.5672,
    activa: true,
  },
  {
    id: "3",
    nombre: "Cacao & Co.",
    descripcion: "Chocolates artesanales con ingredientes de primera calidad. Cajas personalizadas con mensaje.",
    categoria: "chocolateria",
    comuna: "Ñuñoa",
    whatsapp: "+56911111111",
    instagram: "@cacaoyco",
    lat: -33.4569,
    lng: -70.5983,
    activa: true,
  },
  {
    id: "4",
    nombre: "Dulce Disculpa",
    descripcion: "Chocolatería premium con opciones veganas. Trufas, bombones y tabletas artesanales.",
    categoria: "chocolateria",
    comuna: "Vitacura",
    whatsapp: "+56922222222",
    lat: -33.3817,
    lng: -70.5842,
    activa: true,
  },
  {
    id: "5",
    nombre: "Abrazos de Felpa",
    descripcion: "Arreglos con peluches gigantes, flores y globos. El combo perfecto para un perdón de verdad.",
    categoria: "peluches",
    comuna: "Santiago Centro",
    whatsapp: "+56933333333",
    instagram: "@abrazosdefelpa",
    lat: -33.4569,
    lng: -70.6483,
    activa: true,
  },
  {
    id: "6",
    nombre: "El Gesto Justo",
    descripcion: "Regalos curados especialmente para mujeres. Velas, perfumes, joyería y accesorios.",
    categoria: "regalos",
    comuna: "Providencia",
    whatsapp: "+56944444444",
    instagram: "@elgestojusto",
    lat: -33.4328,
    lng: -70.6093,
    activa: true,
  },
];
